export const DATABASE_HOST = 'DATABASE_HOST';
export const DATABASE_PORT = 'DATABASE_PORT';
export const DATABASE_USER = 'DATABASE_USER';
export const DATABASE_PASS = 'DATABASE_PASS';
export const DATABASE_DB = 'DATABASE_DB';